sendToFriendInput:
  customize:
    sendDraftButton:
      template: [message, sendDraftButton]
      parts   : [formMessage]
      target  : [formBottom]
all:
  has_layout:     on
  layout:         layoutB
